### PR TITLE
distinguish between empty 200 response and 404 not found

### LINKED ISSUE #120: `get` invocation for a non-existent `kv` file returns an empty Blob instead of 404ing
Test to show this failing added here:
https://github.com/spruceid/kepler-sdk/pull/43

### PR DESCRIPTION
**Pull request by chunningham**
Fix #120 by adding an extra `InvocationResponse` case representing not-found. existing `Empty` case results in a `200` success response

### CODE REVIEW

File: src/routes/mod.rs [hunk 1]
```diff
@@ -154,14 +154,14 @@ pub async fn handle_kv_action(
...
-            Ok(InvocationResponse::Empty)
+            Ok(InvocationResponse::EmptySuccess)
         }
         KVAction::Get { orbit, key } => match orbit.service.read(key).await {
             Ok(Some((md, r))) => Ok(InvocationResponse::KVResponse(KVResponse::new(
                 Metadata(md),
                 r,
             ))),
-            _ => Ok(InvocationResponse::Empty),
+            _ => Ok(InvocationResponse::NotFound),
```
Comment (sbihel) [inline src/routes/mod.rs:164]: Should return a 500 on an error no?

**Review by sbihel — APPROVED** [review]

File: src/routes/mod.rs [hunk 2]
```diff
@@ -229,7 +231,8 @@ pub enum InvocationResponse {
 impl<'r> Responder<'r, 'static> for InvocationResponse {
     fn respond_to(self, request: &'r Request<'_>) -> rocket::response::Result<'static> {
         match self {
-            InvocationResponse::Empty => ().respond_to(request),
+            InvocationResponse::NotFound => Option::<()>::None.respond_to(request),
+            InvocationResponse::EmptySuccess => ().respond_to(request),
```
Comment (cobward) [inline src/routes/mod.rs:235]: NABD but this could be clearer using the impl for `(Status, R)`.
```suggestion
            InvocationResponse::NotFound => (Status::NotFound, ()).respond_to(request),
            InvocationResponse::EmptySuccess => ().respond_to(request),
```

**Review by cobward — APPROVED** [review]
Just a small suggestion, otherwise lgtm

File: src/routes/mod.rs (hunk 2 above)
Comment (chunningham) [reply src/routes/mod.rs:235]: Merged before I realised there was another comment :(
